aws:
  region: us-east-1
  queue_url: "devxp-portal-orders"
  dlq_url: "devxp-portal-orders"
  profile: ""
printer:
  name: "Epson"
  mode: "RAW"
worker:
  max_number_of_messages: 5
  wait_time_seconds: 10
  backoff_seconds: 15
logging:
  level: "INFO"
